apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","automountServiceAccountToken":false,"kind":"ServiceAccount","metadata":{"annotations":{},"name":"lab07-app-sa","namespace":"default"}}
  creationTimestamp: "2026-09-30T14:38:08Z"
  name: lab07-app-sa
  namespace: default
  resourceVersion: "24031"
  uid: 04255526-5999-4536-8037-abfb549035b3
